### ISSUE TITLE
Save as new name

### ISSUE THREAD

**Issue by 1Adamcom** [plrthink/react-native-file-download#1]
Hi,

How can i save as file with new name ?

Thanks.

**Comment by plrthink** [comment]
@1Adamcom It doesn't support this feature, but I think it should be simple to be implemented. I will do that when I have time or you can open a pr for that.

**Comment by 1Adamcom** [comment]
Ok, i used react-native-fs for rename after download complated. thanks for download module.

**Comment by plrthink** [comment]
@1Adamcom yeah, actually I'm also using react-native-fs in my project to get me access to the file system such as get me the document path which I would use as`target` argument of the react-native-file-download's download function.

**Comment by plrthink** [comment]
@1Adamcom I think I should mention that in README.md for better using this plugin, I will do that.
