### ISSUE TITLE
Anyone else getting "no visible @interface for 'RNFileDownloadSessionManager' declares the selector 'initWithTargetPath:downloadFileName:headers:bridge:callback:'"

### ISSUE THREAD

**Issue by brianinator** [plrthink/react-native-file-download#6]
I rewrote the call to: 
`RNFileDownloadSessionManager *manager = [[RNFileDownloadSessionManager alloc] initWithTargetPath:targetPath downloadFileName:fileName bridge:self.bridge callback:callback];`

Eliminating the new line formatting and then did a project clean and build, it then worked. 

Anyone else experiencing the same?

**Comment by plrthink** [comment]
@devbriguy I just published a new version on npm, it fixes the problem on my side. Could you give it a try?

**Comment by brianinator** [comment]
@plrthink I did a npm update and this one was not updated. It's still "react-native-file-download": "0.0.8" or that is the latest?

**Comment by plrthink** [comment]
@devbriguy I published 0.0.9 last night. Maybe you should manually update it in package.json and run npm install.

**Comment by brianinator** [comment]
All good now. Thanks!
